five_prime_UTR = "AATCTAGTATGCTCTAAACCCTTTTTGCTAACTCTATAAAATCCCCTCACAAATCCTTAATTCACCTCTTCCCCTTCGCTCTCGAATCAATCACTCTCTCTTCTTTAGCGTTTTTATTTTGTCTTCCTCGTTTTCTTCTACCTTTTTATATTTTCTCTCTTTTCAGTTTTCTCTAGAAAAAAACACTAGTAATCAGTTTGCGTTTGATAAATATTTGATGTGGCAAAACTCTTGTGGATCTTGATGTTCAAACATTCATGTCTCCGGTGATTAGTGAAATCCTTAGATCTGGTTTAACTATAGACTCGTCTCTTAGACGCAGGACCCATCTTGTTCAATCTTTCTCCGTCGTCTTTCTCTACTGGTTCTATGTTTTCTCATAAATCAGCTCTCCTTTAGCCCTTTATTATTATATATTCTATAACCATAATAATATATTAAAACTATATACTATAATCTTTTTACATAATAAACTTTGGGTCCTGCGTCTTAATCATAGTACTTAATTTTCTCTGTGTGTTTTAAT"

start_codon = ["ATG"]
end_codon = ["TAA", "TAG", "TGA"]

for i in range(len(five_prime_UTR)):
    # 枚举 i 作为起始密码子第一个碱基的位置
    if five_prime_UTR[i:i+3] in start_codon:
        # 如果起始密码子在 i 位置
        # 枚举 j 作为终止密码子第一个碱基的位置
        for j in range(i, len(five_prime_UTR), 3):
            # 如果终止密码子在 j 位置
            if five_prime_UTR[j:j+3] in end_codon:
                print(five_prime_UTR[i:j+3])
                break
